wkbotsfeeder: Add 'mute' command that allows silent notifications from a builder
psaavedra/matrix-bot pull request #56
Opened 2021-03-18 02:07 UTC by dpino

I tested it with an unit test, but I don't know actually how receiving command works.

2021-03-18 16:25 UTC, psaavedra commented on matrixbot/plugins/wkbotsfeeder.py
> +    def command(self, sender, room_id, body, handler = None):
body will be something like `mybotname: command arg1 arg2 ...`

2021-03-18 16:32 UTC, psaavedra commented on matrixbot/plugins/wkbotsfeeder.py
>      def help(self, sender, room_id, handler):
You could make the [`def usage()`](https://github.com/psaavedra/matrix-bot/pull/56/files#diff-9210bba16129d7d645d5fae49dfab47565db1b8999336573faa6a774a05e6d30R130) a class method and reuse it here.

Or just:
``` python
    def help(self, sender, room_id, handler):
        self.logger.debug("WKBotsFeederPlugin")
        message = "blah ..."
        handler(room_id, message)
```

The rationale behind this is to get this command help listed by the `help` command.

2021-03-18 16:33 UTC, psaavedra requested changes
Looks good. Just as couple of suggestions regarding the help command.

2021-03-19 00:33 UTC, dpino commented
Thanks for the review. I amended the patch to address suggested changes.

2021-03-19 10:26 UTC, psaavedra requested changes

2021-03-19 10:26 UTC, psaavedra commented on matrixbot/plugins/wkbotsfeeder.py
> +        if value not in ["on", "off"]:
I like a lot this way to interact with the plugin object. Nice idea.

2021-03-19 10:26 UTC, psaavedra commented on matrixbot/plugins/wkbotsfeeder.py
> +        message = "<p>mute <builder-name> [ON|OFF]<p>"
Did you tried this? I  think <p> are not needed. Other plugins don't use that.

2021-03-19 10:26 UTC, psaavedra commented on matrixbot/plugins/wkbotsfeeder.py
> +        message = "<p>mute <builder-name> [ON|OFF]<p>"
... for example the plugin/trac.py uses: `message = "%(name)s create This is the issue summary\n" % self.settings`

2021-04-20 19:28 UTC, merged